# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e30237d57bf09d335106539c0040cade27868a7be9f36f71cfdea583f0f4b9a32fe8bde4f46dce735720485e0f11f82f33270a5d8c52691db19aab363ba4f288

test:
  secret_key_base: c265a4c336bfbd29c9c5b9cc43befe4b2f7631f53878da4853a02e6b3c7b5537806c8108e509c544929d24136d5d22b80e582502020a07a68e4ad0fdc1a3f2a9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
